### ISSUE TITLE
がたつきの修正とロゴの色

### ISSUE THREAD

**Issue by spicagraph** [WordBenchOsaka/wapuu-takoyaki#2]
https://github.com/WordBenchOsaka/wapuu-takoyaki/commit/61782a5924cf96132251107ec63daf3512588b34
このコミットの際に、原因は不明ですが耳や尻尾の一部ががたついてしまいました。
それを修正したいです。
あと、ロゴの白が70％透明度になっていましたが、印刷でもsvgでも透明度は100％にしたほうがいいかなと思うので修正したいです。

**Comment by nipper-onside** [comment]
> ロゴの白が70％透明度になっていましたが

半透明にした理由を思い出せませんが、おそらく背景（たこ焼き）に馴染ませるためだった気がします。
ですので、ロゴマークをたたせたいということであれば、半透明にしなくてもいいんじゃないですか。

**Comment by spicagraph** [comment]
@nipper-onside 
元々のデータでは100％でした、大丈夫です！
すみません説明不足で、ここ数日で幾つか修正してまして、 @gouten5010 さんの修正でなじませるために半透明にしてもらったと思うんですが、なんだか怖くて^^; ごうてんさんごめんなさい！！

**Comment by nipper-onside** [comment]
@spicagraph
了解っす。
ずいぶん前のことなので全然覚えてなかったです w

**Comment by spicagraph** [comment]
みなさんありがとうございますーcloseします！
https://github.com/WordBenchOsaka/wapuu-takoyaki/pull/3#issuecomment-247102158
