### ISSUE TITLE
wapuu と wapuu-takoyaki リポジトリ

### ISSUE THREAD

**Issue by ixkaito** [WordBenchOsaka/wapuu-takoyaki#4]
- なんで wapuu と wapuu-takoyaki の二つのリポジトリがあるんですか？
- wappu-takoyaki じゃなく、名前に合わせて takoyaki-wapuu の方がよくないですか？

**Comment by gouten5010** [comment]
@ixkaito 回答遅れてスミマセン。
名前は変えましょう。

wapuuリポジトリは[本家]([wapuu-api](https://github.com/jawordpressorg/wapuu)からForkしてるやつなので、間違って本家にPushしてしまう事例がありました。（マージはされないですけど）
それを受けて、別リポジトリ運用することにしています。

わぷーアーカイブの掲載の際もForkを必要としなくなったので、本家の[wapuu-api](https://github.com/jawordpressorg/wapuu-api)のリポジトリにプルリク送ってマージされたらForkしたリポジトリは削除する予定。
1. リポジトリの名前の変更
2. [wapuu-api](https://github.com/jawordpressorg/wapuu-api)にこのリポジトリの情報に変更したものをプルリク
3. マージされたらForkしたリポジトリの削除

**Comment by ixkaito** [comment]
@gouten5010 

> 間違って本家にPushしてしまう事例がありました。

なるほど。ではフォークの方は削除するんですか？上記理由であれば削除した方がいいと思いますが。

**Comment by ixkaito** [comment]
@gouten5010 

名前の変更は issue 出しときます。

**Comment by gouten5010** [comment]
@ixkaito 
はい、先の返信にあるように、wapuu-apiにプルリク出してマージされたら、wapuuのリポジトリは削除します。

> 1. リポジトリの名前の変更
> 2. wapuu-apiにこのリポジトリの情報に変更したものをプルリク
> 3. マージされたらForkしたリポジトリの削除

タスクとして #5 のほうでチェックボックス追加しました。

**Comment by gouten5010** [comment]
一旦この話題Closeします。

**Comment by ixkaito** [comment]
@gouten5010 

[WordBenchOsaka/wapuu](https://github.com/WordBenchOsaka/wapuu) は [jawordpressorg/wapuu-api](https://github.com/jawordpressorg/wapuu-api) のフォークじゃないからプルリク出せないですよ？もう削除してもいいと思いますが。

**Comment by gouten5010** [comment]
@ixkaito 
わぷーアーカイブでリンクされてるのはリポジトリURLか…
それだけなら削除してよさそうですね。
